system:
  allow-register: false
  username-length:
    min: 6
    max: 18
  password-length:
    min: 6
    max: 18
  salt:
    size: 6
    hash-count: 4
  file-upload:
    path: /upload
    absolute: false