#验证码设置
captcha:
  cacheName: captcha
  cookieName: captcha-cache
  cookieMaxAge: -1
  captchaBackgroundColor: '#ffffff'
  captchaSize: 4
  captchaLineCount: 2
  captchaPointCount: 2
  captchaWidth: 76
  captchaHeight: 36
  captchaFontSize: 20
  captchaHasBorder: false
  captchaIsColorful: true
