spring:
  freemarker:
    cache: false
  profiles:
    active:
    - single-datasource
    - setting
server:
  port: 8080
  servlet:
    context-path: /blog
logging:
  level:
    com.yang.blog: info
mybatis-plus:
  global-config:
    db-config:
      id-type: