spring:
  fastjson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  freemarker:
    cache: false
  profiles:
    active:
      - dev
      - single-datasource
      - setting
      - shiro-captcha
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true
server:
  port: 8080
  #下面4条属性与nginx配置对应，解决nginx反向代理后，https变成http问题
  use-forward-headers: true
  tomcat:
    #  nginx配置：
    #  proxy_redirect off;
    #  proxy_set_header Host $host;
    #  proxy_set_header X-Real-IP $remote_addr;
    #  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #  proxy_set_header X-Forwarded-Proto $scheme;
    #
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
logging:
  level:
    com.yang.blog: info
