spring:
  freemarker:
    cache: false
  profiles:
    active:
    - single-datasource
    - setting
    - shiro-captcha
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
server:
  port: 8080
logging:
  level:
    com.yang.blog: debug
