spring:
  fastjson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
  freemarker:
    cache: false
  profiles:
    active:
      - dev
      - single-datasource
      - setting
      - shiro-captcha
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true
server:
  port: 8080
logging:
  level:
    com.yang.blog: info
